### ISSUE TITLE
Add S-PLUS filters

### ISSUE THREAD

**Issue by splus-github-user** [gaia-dpci/GaiaXPy#53] opened 2023-04-24 16:37 UTC
Thank you very much for making this wonderful tool available.

I am a member of the S-PLUS survey, and I am reaching out on behalf of our community. I would like to check if it is possible to add these filters to gaiaxpy. This would be incredibly valuable for validating the calibration of a sub-survey. The transmission curves can be found at http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse&gname=CTIO&gname2=S-PLUS&asttype=

Thank you once again!
Helio Perottoni

**Comment by fdeangeli** [comment] 2023-04-24 18:48
Thank you for your kind comment.

In collaboration with the SVO team, all filters available from http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse can already be used to generate synthetic photometry with GaiaXPy. Please see instructions on how to download the correct configuration files at 
https://gaia-dpci.github.io/GaiaXPy-website/tutorials/SVO%20download.html
and a tutorial on how to load them into GaiaXPy at
https://gaia-dpci.github.io/GaiaXPy-website/tutorials/Additional%20systems%20tutorial.html

I hope you will find this useful.
Kind regards,
Francesca

**Comment by splus-collab** [comment] 2023-05-04 14:21
Dear Francesca,

As you suggested, I have downloaded the transmission curves from S-PLUS (http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse&gname=CTIO&gname2=S-PLUS&asttype=). However, after running the code, I have observed that the u band is not being accounted for in the synthetic magnitude produced by the code. I am unsure of the cause of this issue. Could you help me?

Best,
Helio

**Comment by fdeangeli** [comment] 2023-05-23 08:06
Sorry for the dalay in getting back to you.
Only filters that were fully covered by BP/RP were generated from the SVO database. The u band from S-PLUS extends beyond the blue edge of the wavelength range covered by BP (approximately 330 nm). 
In previous investigations with other u bands, we have found more useful artificially cutting the band at 330 or 335 nm. This will of course leave a colour term, but this is unavoidable in any case. If you think this might be useful, we can produce an ad hoc filter for the u from S-PLUS cut at 330 nm and provide it to you. You will then be able to load it as done for the SVO filters.

**Comment by fdeangeli** [comment] 2023-12-12 14:56
I plan to close this issue in one week (19th of December) if there are no further replies.

**Comment by herpichfr** [comment] 2023-12-14 00:03
Hi Francesca.

Please go ahead and close the issue. I understand that the S-PLUS team worked around the u-band issue, even applying Gaia corrections to the S-PLUS magnitudes using the GaiaXPy code. Thank you for the feedback and valuable suggestions.

**Closed** 2023-12-14 08:37 UTC

**Comment by fdeangeli** [comment] 2023-12-14 08:38
No further action required.
